#!/usr/bin/env python2

import sys


def no_errors(verdicts, score):
    sorting_order = ['JE', 'IF', 'RTE', 'MLE', 'TLE', 'OLE', 'WA', 'PE', 'REJ', 'AC']
    verdicts += ['AC']
    index = min(sorting_order.index(verdict) for verdict in verdicts)
    return sorting_order[index]


def always_accept(verdicts, score):
    return 'AC'


def accept_if_nonzero(verdicts, score):
    return 'AC' if score != 0 else 'REJ'


verdict_aggregators = {
    'no_errors': no_errors,
    'always_accept': always_accept,
    'accept_if_nonzero': accept_if_nonzero
}


def avg(scores):
    return 1.0*sum(scores) / len(scores)


score_aggregators = {
    'sum': sum,
    'avg': avg,
    'max': max,
    'min': min
}

aggregate_scores = score_aggregators['sum']
aggregate_verdicts = verdict_aggregators['no_errors']

for flag in sys.argv:
    if flag in score_aggregators:
        aggregate_scores = score_aggregators[flag]
    if flag in verdict_aggregators:
        aggregate_verdicts = verdict_aggregators[flag]

try:
    data = sys.stdin.read().split()
    verdicts = data[0::2]
    scores = map(float, data[1::2])
    score = aggregate_scores(scores)
    print '%s %f' % (aggregate_verdicts(verdicts, score), score)
except:
    print 'JE 0'

sys.exit(0)
